spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/phoneshop
    username: phoneshop
    password: 123123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
